# Generated by Django 6.0.1 on 2026-01-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appointments', '0002_initial'),
        ('Dentists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dentists.clinic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dentists.dentists'),
        ),
    ]
